### ISSUE TITLE
VR Interaction Todo

### ISSUE THREAD

**Issue by xthexder** [frustra/strayphotons#277]
- [x] Physics query update to add overlap and sweep queries
- [x] Read in correct OpenVR hand poses
- [x] Define input focus via script "grab" events
- [ ] Use physx custom constraint implementation for force constraints
